### ISSUE TITLE
Doesn't work with diff-lcs 1.4 and later

### ISSUE THREAD

**Issue by yujideveloper** [nishio-dens/convergence#75]
## Overview

I got an error when using convergence with diff-lcs v1.4.2.

### table

``` sql
CREATE TABLE `test_tables` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_test_tables_on_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT
```

### schema file

``` ruby
create_table 'test_tables' do |t|
  t.int :id, primary_key: true, extra: 'auto_increment'
  t.varchar :name, limit: 100, null: true
  t.varchar :email, null: true
  t.datetime :created_at
  t.datetime :updated_at

  t.index :name
end
```
### command

``` bash
convergence apply example.schema -c database.yml
```

### errors

```
$ convergence apply example.schema -c database.yml
Traceback (most recent call last):
        17: from /home/yujideveloper/.rbenv/versions/2.7.1/bin/convergence:23:in `<main>'
        16: from /home/yujideveloper/.rbenv/versions/2.7.1/bin/convergence:23:in `load'
        15: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/bin/convergence:6:in `<top (required)>'
        14: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        13: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        12: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        11: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        10: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/cli.rb:24:in `apply'
         9: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/command/apply.rb:13:in `execute'
         8: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/command/apply.rb:38:in `execute_sql'
         7: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/command/apply.rb:21:in `generate_sql'
         6: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:12:in `diff'
         5: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:49:in `scan_change_table'
         4: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:49:in `each'
         3: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:52:in `block in scan_change_table'
         2: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:27:in `diff_table'
         1: from /home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:103:in `scan_change_order_column'
/home/yujideveloper/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/convergence-1.0.3/lib/convergence/diff.rb:103:in `select': undefined method `adding?' for "+":String (NoMethodError)
```

### env

* ruby: 2.7.1
* convergecne: v1.0.3
* diff-lcs: v1.4.2

**Comment by yujideveloper** [comment]
I think this is caused by halostatue/diff-lcs#47.
